name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - requests>=2.28.0
  - pydantic>=2.0.0
  - pip:
      - mlflow==2.18.0
      - wandb==0.19.8
