name: nyc_airbnb2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - jupyterlab=4.0.9
  - scikit-learn=1.3.1
  - numpy=1.24.4
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.19.8