name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - requests=2.24.0
  - pyarrow
  - pip:
      - mlflow==2.18.1
      - wandb==0.19.8
      - git+https://github.com/bbro837/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
